service: ocpp-backend

plugins:
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-offline

custom:
  connectionTable: 'connectionTable'
  # dynamodb:
  #   start:
  #     inMemory: true
  #     migrate: true
  #     dbPath: "./.dynamodb"
  #   installPath: ./.dynamodb
  #   stages:
  #     - dev
  serverless-offline:
    websocketPort: 3001
    httpPort: 3002
    # lambdaPort: 3008
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  websocketsApiName: ocpp-websocket
  websocketsDescription: OCPP-J Websocket Server
  # timeout: 30
  environment:
    CONNECTION_TABLE: ${self:custom.connectionTable}
  logs:
    websocket: true

functions:
  connectionHandler:
    handler: src/handlers/connection.handler
    events:
      - websocket:
          route: $connect
          # authorizer: auth
  messageHandler:
    handler: src/handlers/message.handler
    events:
      - websocket:
          route: $default
        # routeResponseSelectionExpression: "request.body.action"
  disconnectionHandler:
    handler: src/handlers/disconnect.handler
    events:
      - websocket:
        route: $disconnect
  
resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
