service: ocpp-backend

plugins:
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-offline

custom:
  serverless-offline:
    websocketPort: 3001
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  websocketsApiName: ocpp-websocket
  # websocketsApiRouteSelectionExpression: $request.body.route
  websocketsDescription: OCPP-J Websocket Server
  logs:
    websocket: true

functions:
  connectionHandler:
    handler: connection.handler
    events:
      - websocket:
          route: $connect
          # authorizer: auth
      - websocket:
          route: $disconnect
      - websocket:
          route: ${request.body.action}
  auth:
    handler: auth.handler
  messageHandler:
    handler: message.handler
    events:
      - websocket:
          route: ${request.body.action}
  defaultHandler:
    handler: default.handler
    events:
      - websocket: $default
  