service: ocpp-backend

plugins:
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-offline

custom:
  serverless-offline:
    websocketPort: 3001
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  websocketsApiName: ocpp-websocket
  websocketsDescription: OCPP-J Websocket Server
  logs:
    websocket: true

functions:
  connectionHandler:
    handler: src/handlers/connection.handler
    events:
      - websocket:
          route: $connect
          # authorizer: auth
      - websocket:
          route: $disconnect
  auth:
    handler: src/handlers/auth.handler
  messageHandler:
    handler: src/handlers/message.handler
    events:
      - websocket:
          route: $default
        # routeResponseSelectionExpression: "request.body.action"
  